from abc import ABC, abstractmethod
from models.resume_data import ResumeData

class BaseTemplate(ABC):
    @abstractmethod
    def generate(self, resume_data: ResumeData) -> str:
        """Generates the LaTeX version of the resume based on the specific template structure."""
        pass
    
    def escape_latex(self, text: str) -> str:
        """Escapes common LaTeX special characters."""
        if not text:
            return ""
        # Simple escaping for basic user input
        text = text.replace('\\', '\\textbackslash{}')
        text = text.replace('&', '\\&')
        text = text.replace('%', '\\%')
        text = text.replace('$', '\\$')
        text = text.replace('#', '\\#')
        text = text.replace('_', '\\_')
        text = text.replace('{', '\\{')
        text = text.replace('}', '\\}')
        text = text.replace('~', '\\textasciitilde{}')
        text = text.replace('^', '\\textasciicircum{}')
        return text

    def _get_latex_preamble(self):
        return r"""%-------------------------
% Resume generated by CareerLoom
%------------------------

\documentclass[letterpaper,11pt]{article}
\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\usepackage{fontawesome5}
\usepackage{multicol}
\setlength{\multicolsep}{-3.0pt}
\setlength{\columnsep}{-1pt}
\pagestyle{fancy}
\fancyhf{} % clear all header and footer fields
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
% Adjust margins
\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1.19in}
\addtolength{\topmargin}{-.7in}
\addtolength{\textheight}{1.4in}
\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}
% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large\bfseries
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]
\pdfgentounicode=1

% Custom commands
\newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-2pt}}}}
\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{1.0\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & \textbf{\small #2} \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}
\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{1.001\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & \textbf{\small #2}\\
    \end{tabular*}\vspace{-7pt}
}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.0in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}
"""

    def _format_header(self, personal_info):
        name = self.escape_latex(personal_info.full_name)
        phone = self.escape_latex(personal_info.phone)
        email = self.escape_latex(personal_info.email)
        links = self.escape_latex(personal_info.links)
        
        # Build the contact line based on what's available
        contact_parts = []
        if phone:
            contact_parts.append(rf"\raisebox{{-0.1\height}}\faPhone\ {phone}")
        if email:
            contact_parts.append(rf"\href{{mailto:{email}}}{{\raisebox{{-0.2\height}}\faEnvelope\ \underline{{{email}}}}}")
        
        contact_line_1 = " ~ ".join(contact_parts)
        
        # For links, we assume they are URLs if provided, or we just render them
        # as a generic globe/link icon. A smarter parser would detect LinkedIn/GitHub.
        contact_line_2 = ""
        if links:
            # We just use a link icon for generic links for now
            contact_line_2 = rf"\href{{{links}}}{{\raisebox{{-0.2\height}}\faLink\ \underline{{{links}}}}}"

        header = rf"""\begin{{center}}
    {{\Huge \scshape {name}}} \\ \vspace{{1pt}}
    \small {contact_line_1} \\
    {contact_line_2}
    \vspace{{-8pt}}
\end{{center}}
"""
        return header

    def _format_skills(self, skills):
        if not skills:
            return ""
        skills_escaped = self.escape_latex(skills)
        return rf"""\section{{Technical Skills}}
 \begin{{itemize}}[leftmargin=0.15in, label={{}}]
    \small{{\item{{
     \textbf{{Skills}}{{: {skills_escaped}}}
    }}}}
 \end{{itemize}}
"""

    def _format_education(self, education_list):
        if not education_list:
            return ""
        
        items = []
        for edu in education_list:
            degree = self.escape_latex(edu.degree)
            inst = self.escape_latex(edu.institution)
            year = self.escape_latex(edu.year)
            score_str = f", Score: {self.escape_latex(edu.score)}" if edu.score else ""
            
            # Using resumeSubheading: title, date, subtitle, location
            # Here: Institution, Year, Degree + Score, ""
            items.append(rf"      \resumeSubheading{{{inst}}}{{{year}}}{{{degree}{score_str}}}{{}}")
            
        inner_content = "\n".join(items)
        return rf"""\section{{Education}}
  \resumeSubHeadingListStart
{inner_content}
  \resumeSubHeadingListEnd
"""

    def _format_projects(self, project_list):
        if not project_list:
            return ""
        
        items = []
        for proj in project_list:
            title = self.escape_latex(proj.title)
            tech = self.escape_latex(proj.tech_stack)
            desc = self.escape_latex(proj.description)
            
            tech_str = f" $|$ \emph{{{tech}}}" if tech else ""
            
            items.append(rf"    \resumeProjectHeading{{\textbf{{{title}}}{tech_str}}}{{}}")
            if desc:
                items.append(rf"    \resumeItemListStart")
                items.append(rf"      \resumeItem{{{desc}}}")
                items.append(rf"    \resumeItemListEnd")
            
        inner_content = "\n".join(items)
        return rf"""\section{{Projects}}
  \resumeSubHeadingListStart
{inner_content}
  \resumeSubHeadingListEnd
"""

    def _format_experience(self, experience_list):
        if not experience_list:
            return ""
        
        items = []
        for exp in experience_list:
            role = self.escape_latex(exp.role)
            company = self.escape_latex(exp.company)
            duration = self.escape_latex(exp.duration)
            resp = self.escape_latex(exp.responsibilities)
            
            items.append(rf"    \resumeSubheading{{{company}}}{{{duration}}}{{{role}}}{{}}")
            if resp:
                items.append(rf"    \resumeItemListStart")
                items.append(rf"      \resumeItem{{{resp}}}")
                items.append(rf"    \resumeItemListEnd")
            
        inner_content = "\n".join(items)
        return rf"""\section{{Experience}}
  \resumeSubHeadingListStart
{inner_content}
  \resumeSubHeadingListEnd
"""
